<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        /* @var $this Zend_View */
        echo $this->headTitle($this->translate('My Application'))->setSeparator(' - ')->setAutoEscape(false);

        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="header">
            <?php
                $user = $this->identity();

                if ( $user ) {
                    echo $this->top_nav();
                }
            ?>

            <div class="title">
                <div class="container">
                    <h1>&nbsp My Application</h1>
                </div>
            </div>

        </div>

        <div class="content">
            <div class="container">
                <?= $this->page_header(); ?>
                <?= $this->layout()->content ?>
            </div>
        </div>

        <div class="container footer">
            <p class="muted text-center">
                Site created and maintained by XXX / &copy; All Rights Reserved
                <br />
                Address Here
            </p>
        </div>

        <div class="print-footer">
            <p>
                Generated on <?=date('l jS \of F Y h:i:s A')  ?>
            </p>
        </div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
